---
- name: Install with pip (incl. executable)
  pip:
    name: "{{ gunicorn_pip_packages }}"
    state: present
    version: "{{ gunicorn_pip_version | default(omit) }}"
    executable: "{{ gunicorn_pip_executable | default(omit) }}"
  tags:
    - gunicorn_pip
    - gunicorn_install
  when:
    - "gunicorn_pip_executable is not none"

- name: Install certbot with pip (venv) - with command
  pip:
    name: "{{ gunicorn_pip_packages }}"
    state: present
    version: "{{ gunicorn_pip_version | default(omit) }}"
    virtualenv: "{{ gunicorn_pip_virtualenv | default(omit) }}"
    virtualenv_command: "{{ gunicorn_pip_virtualenv_command }}"
    virtualenv_python: "{{ gunicorn_pip_virtualenv_python | default(omit) }}"
    virtualenv_site_packages: "{{ gunicorn_pip_virtualenv_site_packages | default(omit) }}"
  tags:
    - gunicorn_pip
    - gunicorn_install
  when:
    - "gunicorn_pip_executable is none"
    - "gunicorn_pip_virtualenv is not none"
    - "gunicorn_pip_virtualenv_command is not none"

- name: Install certbot with pip (venv) - no command
  pip:
    name: "{{ gunicorn_pip_packages }}"
    state: present
    version: "{{ gunicorn_pip_version | default(omit) }}"
    virtualenv: "{{ gunicorn_pip_virtualenv | default(omit) }}"
    virtualenv_python: "{{ gunicorn_pip_virtualenv_python | default(omit) }}"
    virtualenv_site_packages: "{{ gunicorn_pip_virtualenv_site_packages | default(omit) }}"
  tags:
    - gunicorn_pip
    - gunicorn_install
  when:
    - "gunicorn_pip_executable is none"
    - "gunicorn_pip_virtualenv is not none"
    - "gunicorn_pip_virtualenv_command is not none"

# Tempted to allow only installs of systemd files for
# ansible_service_mgr == 'systemd' hosts, but I'll leave it for now.
# There may be some instance where someone wants to install the files without
# using the service... maybe?
- name: Install certbot systemd service
  template:
    src: gunicorn.service.j2
    dest: "/etc/systemd/system/{{ gunicorn_renew_systemd_name }}.service"
    owner: root
    group: root
    mode: "0644"
  notify:
    - systemctl daemon-reload
  when:
    - "not gunicorn_cron"
