---
# tasks file for ansible-role-gunicorn
- name: Get role-based facts
  include_tasks: gather_role_facts.yml

- name: Install epel-release (CentOS)
  package:
    name: epel-release
    state: present
  register: epel_install
  when:
    - "gunicorn_install_epel|bool"
    - "ansible_os_family == 'RedHat'"

- name: Install dependency packages
  package:
    name: "{{ _gunicorn_packages }}"
    state: present
    update_cache: "{{ epel_install.changed }}"
  when:
    - "not gunicorn_pip_enabled|bool"

- name: Install with pip
  include_tasks: install-pip.yml
  when:
    - "gunicorn_pip_enabled|bool"

- name: Install the gunicorn config file
  template:
    src: gunicorn.conf.py.j2
    dest: "{{ gunicorn_config_path }}"
    owner: "{{ gunicorn_owner }}"
    group: "{{ gunicorn_group }}"
    mode: "{{ gunicorn_config_mode }}"
  notify:
    - restart service

- block:
    - name: Install the systemd service
      template:
        src: gunicorn.service.j2
        dest: "/etc/systemd/system/{{ gunicorn_service_name }}.service"
        owner: root
        group: root
        mode: "0644"
      register: _gunicorn_service_installed

    - name: Install the systemd socket
      template:
        src: gunicorn.socket.j2
        dest: "/etc/systemd/system/{{ gunicorn_service_name }}.socket"
        owner: root
        group: root
        mode: "0644"
      when:
        - "gunicorn_socket|bool"

    - name: Remove the systemd socket
      file:
        path: "/etc/systemd/system/{{ gunicorn_service_name }}.socket"
        state: absent
      when:
        - "not gunicorn_socket|bool"

    - name: Daemon-reload
      systemd:
        daemon_reload: "{{ gunicorn_service_daemon_reload }}"
      when:
        - "ansible_service_mgr == 'systemd'"
        - "gunicorn_service_daemon_reload"
        - "_gunicorn_service_installed.changed"

- name: Set the service state
  service:
    name: "{{ gunicorn_service_name }}"
    state: "{{ gunicorn_service_state }}"
    enabled: "{{ gunicorn_service_enabled }}"
  when:
    - "gunicorn_service_state is not none"
