---
# handlers file for ansible-role-gunicorn
- name: Systemd daemon reload
  systemd:
    daemon_reload: true
  listen: systemctl daemon-reload
  when:
    - "ansible_service_mgr == 'systemd'"

- name: Restart the service
  service:
    name: "{{ gunicorn_service_name }}"
    state: "{{ gunicorn_service_restarted_state }}"
  listen: restart service
  when:
    - "gunicorn_service_restarted_state is not none"
