---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
#  - name: gunicorn-molecule-centos-7-instance
#    image: "centos:centos7"
#    command: /sbin/init
#    tmpfs:
#      - /run
#      - /tmp
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: gunicorn-molecule-centos-8-instance
    image: "centos:centos8"
    command: /sbin/init
    tmpfs:
     - /run
     - /tmp
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: gunicorn-molecule-debian-buster-instance
    image: debian:buster
  - name: gunicorn-molecule-debian-stretch-instance
    image: debian:stretch
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
verifier:
  name: testinfra
